#!/bin/bash
# ./test script
#set -e # stop when a test fails
xcodebuild test -scheme "Style Generator" -project "Style Generator/Style Generator.xcodeproj" -destination "platform=iOS Simulator,name=iPhone 7,OS=10.1"